// <auto-generated />
using System;
using ArkJsonValidator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkJsonValidator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ArkJsonValidator.Models.FieldRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidatorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("FieldRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ErrorMessage = "PurchaseOrder must be a valid SAP document number (up to 10 digits)",
                            FieldPath = "PurchaseOrder",
                            IsRequired = true,
                            Order = 1,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "sap_document_number"
                        },
                        new
                        {
                            Id = 2,
                            ErrorMessage = "CompanyCode must be a 4-character alphanumeric value",
                            FieldPath = "CompanyCode",
                            IsRequired = true,
                            Order = 2,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "sap_company_code"
                        },
                        new
                        {
                            Id = 3,
                            ErrorMessage = "Vendor is required",
                            FieldPath = "Vendor",
                            IsRequired = true,
                            Order = 3,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "required"
                        },
                        new
                        {
                            Id = 4,
                            ErrorMessage = "Currency must be a valid ISO 4217 3-letter code",
                            FieldPath = "Currency",
                            IsRequired = true,
                            Order = 4,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "sap_currency_code"
                        },
                        new
                        {
                            Id = 5,
                            ErrorMessage = "PostingDate must be in SAP OData date format /Date(epoch)/",
                            FieldPath = "PostingDate",
                            IsRequired = true,
                            Order = 5,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "sap_odata_date"
                        },
                        new
                        {
                            Id = 6,
                            ErrorMessage = "Plant must be a 4-character SAP plant code",
                            FieldPath = "Plant",
                            IsRequired = true,
                            Order = 6,
                            ParametersJson = "{}",
                            TemplateId = 1,
                            ValidatorType = "sap_plant_code"
                        },
                        new
                        {
                            Id = 7,
                            ErrorMessage = "Please provide a valid email address",
                            FieldPath = "email",
                            IsRequired = true,
                            Order = 1,
                            ParametersJson = "{}",
                            TemplateId = 2,
                            ValidatorType = "email"
                        },
                        new
                        {
                            Id = 8,
                            ErrorMessage = "Please provide a valid phone number",
                            FieldPath = "phone",
                            IsRequired = false,
                            Order = 2,
                            ParametersJson = "{}",
                            TemplateId = 2,
                            ValidatorType = "phone"
                        },
                        new
                        {
                            Id = 9,
                            ErrorMessage = "Username must be at least 3 characters",
                            FieldPath = "username",
                            IsRequired = true,
                            Order = 3,
                            ParametersJson = "{\"min\":3}",
                            TemplateId = 2,
                            ValidatorType = "min_length"
                        },
                        new
                        {
                            Id = 10,
                            ErrorMessage = "Username must be at most 50 characters",
                            FieldPath = "username",
                            IsRequired = true,
                            Order = 4,
                            ParametersJson = "{\"max\":50}",
                            TemplateId = 2,
                            ValidatorType = "max_length"
                        },
                        new
                        {
                            Id = 11,
                            ErrorMessage = "User must be at least 18 years old",
                            FieldPath = "age",
                            IsRequired = false,
                            Order = 5,
                            ParametersJson = "{\"min\":18}",
                            TemplateId = 2,
                            ValidatorType = "min_value"
                        },
                        new
                        {
                            Id = 12,
                            ErrorMessage = "Please provide a valid URL",
                            FieldPath = "website",
                            IsRequired = false,
                            Order = 6,
                            ParametersJson = "{}",
                            TemplateId = 2,
                            ValidatorType = "url"
                        });
                });

            modelBuilder.Entity("ArkJsonValidator.Models.GroupRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupValidatorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("GroupRules");
                });

            modelBuilder.Entity("ArkJsonValidator.Models.ValidationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validates SAP OData purchase order payload fields",
                            Name = "SAP Purchase Order",
                            Tags = "sap,odata,purchase-order",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validates user registration form fields",
                            Name = "User Registration",
                            Tags = "user,registration,common",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ArkJsonValidator.Models.FieldRule", b =>
                {
                    b.HasOne("ArkJsonValidator.Models.ValidationTemplate", "Template")
                        .WithMany("FieldRules")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ArkJsonValidator.Models.GroupRule", b =>
                {
                    b.HasOne("ArkJsonValidator.Models.ValidationTemplate", "Template")
                        .WithMany("GroupRules")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ArkJsonValidator.Models.ValidationTemplate", b =>
                {
                    b.Navigation("FieldRules");

                    b.Navigation("GroupRules");
                });
#pragma warning restore 612, 618
        }
    }
}
